/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/user/register": {
    post: operations["register_user_api_user_register_post"];
  };
  "/api/user/forgotpassword/{email}": {
    get: operations["reset_password_api_user_forgotpassword__email__get"];
  };
  "/api/user/register/google": {
    post: operations["register_user_api_user_register_google_post"];
  };
  "/api/user/": {
    get: operations["get_user_api_user__get"];
  };
  "/api/user/{user_id}": {
    put: operations["update_user_api_user__user_id__put"];
    delete: operations["delete_user_api_user__user_id__delete"];
  };
  "/api/user/role/{user_id}": {
    put: operations["update_user_role_api_user_role__user_id__put"];
  };
  "/api/user/login": {
    post: operations["login_user_api_user_login_post"];
  };
  "/api/user/login/google": {
    post: operations["login_user_api_user_login_google_post"];
  };
  "/api/user/all": {
    get: operations["get_all_users_api_user_all_get"];
  };
  "/api/user/refresh": {
    post: operations["refresh_token_api_user_refresh_post"];
  };
  "/api/user/logout/{user_id}": {
    post: operations["user_logout_api_user_logout__user_id__post"];
  };
  "/api/user/{user_id}/upload-photo": {
    get: operations["upload_user_personal_photo_api_user__user_id__upload_photo_get"];
  };
  "/api/user/badge/task": {
    put: operations["update_badge_task_progress_api_user_badge_task_put"];
  };
  "/api/user/badges/{badge_id}": {
    put: operations["update_badge_api_user_badges__badge_id__put"];
  };
  "/api/user/badges/{user_id}": {
    get: operations["get_user_badges_api_user_badges__user_id__get"];
  };
  "/api/user/actvity/{activity_id}": {
    put: operations["update_place_avtivity_api_user_actvity__activity_id__put"];
  };
  "/api/user/actvity/{user_id}": {
    get: operations["get_user_activities_api_user_actvity__user_id__get"];
  };
  "/api/user/{user_id}/follow": {
    post: operations["follow_user_api_user__user_id__follow_post"];
  };
  "/api/user/{user_id}/unfollow": {
    post: operations["unfollow_user_api_user__user_id__unfollow_post"];
  };
  "/api/user/{user_id}/mate": {
    post: operations["follow_user_api_user__user_id__mate_post"];
  };
  "/api/user/trip-mate-reqs/{req_id}/approve": {
    post: operations["follow_user_api_user_trip_mate_reqs__req_id__approve_post"];
  };
  "/api/user/interests": {
    post: operations["add_prefs_user_api_user_interests_post"];
  };
  "/api/user/interests/delete": {
    post: operations["follow_user_api_user_interests_delete_post"];
  };
  "/api/item/": {
    get: operations["get_items_api_item__get"];
    post: operations["add_new_item_api_item__post"];
  };
  "/api/item/{item_id}": {
    put: operations["update_item_api_item__item_id__put"];
    delete: operations["delete_item_api_item__item_id__delete"];
  };
  "/api/place/": {
    get: operations["get_places_api_place__get"];
    post: operations["add_new_place_api_place__post"];
  };
  "/api/place/activityid": {
    get: operations["get_some_places_api_place_activityid_get"];
  };
  "/api/place/title": {
    get: operations["get_place_by_title_api_place_title_get"];
  };
  "/api/place/{place_id}": {
    get: operations["get_place_by_id_api_place__place_id__get"];
    put: operations["update_place_api_place__place_id__put"];
    delete: operations["delete_place_api_place__place_id__delete"];
  };
  "/api/place/city/{city_name}": {
    get: operations["get_place_by_id_api_place_city__city_name__get"];
  };
  "/api/place/review/{place_id}": {
    post: operations["add_new_review_api_place_review__place_id__post"];
    delete: operations["delete_review_api_place_review__place_id__delete"];
  };
  "/api/place/cities/all": {
    get: operations["get_cities_api_place_cities_all_get"];
  };
  "/api/place/favs/{place_id}": {
    post: operations["add_to_favs_api_place_favs__place_id__post"];
    delete: operations["remove_from_favs_api_place_favs__place_id__delete"];
  };
  "/api/post/": {
    get: operations["get_posts_api_post__get"];
    post: operations["add_new_post_api_post__post"];
  };
  "/api/post/{post_id}": {
    put: operations["update_post_api_post__post_id__put"];
    delete: operations["delete_post_api_post__post_id__delete"];
  };
  "/api/post/like/{post_id}": {
    post: operations["add_new_like_api_post_like__post_id__post"];
    delete: operations["delete_post_like_api_post_like__post_id__delete"];
  };
  "/api/post/{post_id}/upload-photo": {
    get: operations["upload_post_photo_api_post__post_id__upload_photo_get"];
  };
  "/api/chatbot/": {
    post: operations["get_chatbot_api_chatbot__post"];
  };
  "/api/upload/confirm-upload": {
    post: operations["confirm_upload_api_upload_confirm_upload_post"];
  };
  "/api/badge/": {
    get: operations["get_items_api_badge__get"];
    post: operations["add_new_badge_api_badge__post"];
  };
  "/api/badge/{badge_id}": {
    put: operations["update_badge_api_badge__badge_id__put"];
    delete: operations["delete_badge_api_badge__badge_id__delete"];
  };
  "/api/tag/": {
    get: operations["get_tags_api_tag__get"];
    post: operations["add_tag_api_tag__post"];
  };
  "/api/tag/{tag_id}": {
    put: operations["update_tag_api_tag__tag_id__put"];
    delete: operations["delete_post_api_tag__tag_id__delete"];
  };
  "/api/tag/users": {
    post: operations["get_tags_api_tag_users_post"];
  };
  "/api/notification/register-device": {
    post: operations["register_token_api_notification_register_device_post"];
  };
  "/api/notification/send": {
    post: operations["send_notification_api_notification_send_post"];
  };
  "/api/status": {
    /** Performs health check and returns information about running service. */
    get: operations["health_check_api_status_get"];
  };
}

export interface components {
  schemas: {
    /** Badge */
    Badge: {
      /** Id */
      id: string;
      /**
       * Progress
       * @default 0
       */
      progress?: number;
      /**
       * Owned
       * @default false
       */
      owned?: boolean;
      /**
       * Pinned
       * @default false
       */
      pinned?: boolean;
    };
    /** BadgeBase */
    BadgeBase: {
      /** Img Url */
      img_url: string;
      /** Place Id */
      place_id: string;
      /** City */
      city: string;
      /** Max Progress */
      max_progress: number;
      /** Title */
      title: string;
      /** Type */
      type: string;
      /** Xp */
      xp: number;
      /** Description */
      description: string;
      /** Badge Tasks */
      badge_tasks: components["schemas"]["visitegypt__core__badges__entities__badge__BadgeTask"][];
    };
    /** BadgeInDB */
    BadgeInDB: {
      /** Img Url */
      img_url: string;
      /** Place Id */
      place_id: string;
      /** City */
      city: string;
      /** Max Progress */
      max_progress: number;
      /** Title */
      title: string;
      /** Type */
      type: string;
      /** Xp */
      xp: number;
      /** Description */
      description: string;
      /** Badge Tasks */
      badge_tasks: components["schemas"]["visitegypt__core__badges__entities__badge__BadgeTask"][];
      /** Id */
      id: string;
    };
    /** BadgeResponse */
    BadgeResponse: {
      /** Id */
      id: string;
      /**
       * Progress
       * @default 0
       */
      progress?: number;
      /**
       * Owned
       * @default false
       */
      owned?: boolean;
      /**
       * Pinned
       * @default false
       */
      pinned?: boolean;
      /**
       * Badge Tasks
       * @default []
       */
      badge_tasks?: components["schemas"]["visitegypt__core__accounts__entities__user__BadgeTask"][];
    };
    /** BadgesPageResponse */
    BadgesPageResponse: {
      /** Current Page */
      current_page: number;
      /** Content Range */
      content_range: number;
      /** Has Next */
      has_next: boolean;
      /** Badges */
      badges?: components["schemas"]["BadgeInDB"][];
    };
    /** Explore */
    Explore: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Imageurl */
      imageUrl: string;
      /** Hints */
      hints: components["schemas"]["Hint"][];
    };
    /** GetTagResponse */
    GetTagResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description?: string;
    };
    /** HTTPErrorModel */
    HTTPErrorModel: {
      /** Errors */
      errors: string[];
      /** Status Code */
      status_code: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Errors */
      errors?: components["schemas"]["ValidationError"][];
    };
    /** HealthCheck */
    HealthCheck: {
      /**
       * Title
       * @description API title
       */
      title: string;
      /**
       * Description
       * @description Brief description of the API
       */
      description: string;
      /**
       * Version
       * @description API server version number
       */
      version: string;
      /** @description API current status */
      status: components["schemas"]["StatusEnum"];
    };
    /** Hint */
    Hint: {
      /** Hint */
      hint: string;
      /** Imageurl */
      imageUrl: string;
    };
    /** ItemBase */
    ItemBase: {
      /** Title */
      title: string;
      /** Short Description */
      short_description: string;
      /** Long Description */
      long_description?: string;
      /** Default Image */
      default_image?: string;
      /** List Of Images */
      list_of_images?: string[];
      /** Place Id */
      place_id?: string;
    };
    /** ItemInDB */
    ItemInDB: {
      /** Title */
      title: string;
      /** Short Description */
      short_description: string;
      /** Long Description */
      long_description?: string;
      /** Default Image */
      default_image?: string;
      /** List Of Images */
      list_of_images?: string[];
      /** Place Id */
      place_id?: string;
      /** Id */
      id: string;
    };
    /** ItemUpdate */
    ItemUpdate: {
      /** Title */
      title?: string;
      /** Short Description */
      short_description?: string;
      /** Long Description */
      long_description?: string;
      /** Default Image */
      default_image?: string;
      /** List Of Images */
      list_of_images?: string[];
      /** Place Id */
      place_id?: string;
    };
    /** ItemsPageResponse */
    ItemsPageResponse: {
      /** Current Page */
      current_page: number;
      /** Content Range */
      content_range: number;
      /** Has Next */
      has_next: boolean;
      /** Items */
      items?: components["schemas"]["ItemInDB"][];
    };
    /** Notification */
    Notification: {
      /**
       * Title
       * @default
       */
      title?: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /** Icon Url */
      icon_url?: string;
      /**
       * Sent Tags
       * @default []
       */
      sent_tags?: components["schemas"]["GetTagResponse"][];
      /**
       * Sent Users Ids
       * @default []
       */
      sent_users_ids?: string[];
    };
    /** NotificationSentResponse */
    NotificationSentResponse: {
      /**
       * Message
       * @default
       */
      message?: string;
    };
    /** PlaceActivityUpdate */
    PlaceActivityUpdate: {
      /** Finished */
      finished?: boolean;
      /** Progress */
      progress?: number;
    };
    /** PlaceBase */
    PlaceBase: {
      /** Title */
      title: string;
      /** Long Description */
      long_description?: string;
      /** Short Description */
      short_description?: string;
      /** Location Description */
      location_description?: string;
      /** Longitude */
      longitude?: number;
      /** Latitude */
      latitude?: number;
      /** Image Urls */
      image_urls?: string[];
      /** Default Image */
      default_image?: string;
      /** Opening Hours */
      opening_hours?: string;
      /** City */
      city?: string;
      /** Ticket Prices */
      ticket_prices?: { [key: string]: unknown };
      /** Category */
      category?: string;
      /**
       * Views
       * @default 0
       */
      views?: number;
      /** Explores */
      explores?: components["schemas"]["Explore"][];
      /** Placeactivities */
      placeActivities?: components["schemas"]["visitegypt__core__places__entities__place__PlaceActivity"][];
    };
    /** PlaceInDB */
    PlaceInDB: {
      /** Title */
      title: string;
      /** Long Description */
      long_description?: string;
      /** Short Description */
      short_description?: string;
      /** Location Description */
      location_description?: string;
      /** Longitude */
      longitude?: number;
      /** Latitude */
      latitude?: number;
      /** Image Urls */
      image_urls?: string[];
      /** Default Image */
      default_image?: string;
      /** Opening Hours */
      opening_hours?: string;
      /** City */
      city?: string;
      /** Ticket Prices */
      ticket_prices?: { [key: string]: unknown };
      /** Category */
      category?: string;
      /**
       * Views
       * @default 0
       */
      views?: number;
      /** Explores */
      explores?: components["schemas"]["Explore"][];
      /** Placeactivities */
      placeActivities?: components["schemas"]["visitegypt__core__places__entities__place__PlaceActivity"][];
      /**
       * Reviews
       * @default []
       */
      reviews?: components["schemas"]["review"][];
      /** Id */
      id: string;
    };
    /** PlacesPageResponse */
    PlacesPageResponse: {
      /** Current Page */
      current_page: number;
      /** Content Range */
      content_range: number;
      /** Has Next */
      has_next: boolean;
      /** Places */
      places?: components["schemas"]["PlaceInDB"][];
    };
    /** PostBase */
    PostBase: {
      /** Caption */
      caption: string;
      /** List Of Images */
      list_of_images?: string[];
      /** Place Id */
      place_id: string;
      /** User Id */
      user_id: string;
      /** User Name */
      user_name: string;
      /** Likes */
      likes?: string[];
    };
    /** PostInDB */
    PostInDB: {
      /** Caption */
      caption: string;
      /** List Of Images */
      list_of_images?: string[];
      /** Place Id */
      place_id: string;
      /** User Id */
      user_id: string;
      /** User Name */
      user_name: string;
      /** Likes */
      likes?: string[];
      /** Id */
      id: string;
    };
    /** PostsPageResponse */
    PostsPageResponse: {
      /** Current Page */
      current_page: number;
      /** Content Range */
      content_range: number;
      /** Has Next */
      has_next: boolean;
      /** Posts */
      posts?: components["schemas"]["PostInDB"][];
    };
    /** ProfileFrame */
    ProfileFrame: {
      /** Id */
      id: number;
      /** Imgurl */
      imgUrl: string;
      /** Type */
      type: number;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
    };
    /** RegisterDeviceTokenRequest */
    RegisterDeviceTokenRequest: {
      /** Device Token */
      device_token?: string;
    };
    /** RegisterDeviceTokenResponse */
    RegisterDeviceTokenResponse: {
      /**
       * Message
       * @default
       */
      message?: string;
    };
    /** RequestTripMate */
    RequestTripMate: {
      /** Title */
      title: string;
      /** Description */
      description: string;
    };
    /** RequestTripMateInDB */
    RequestTripMateInDB: {
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Id */
      id: string;
      /** Initator Id */
      initator_id: string;
      /** Is Approved */
      is_approved: boolean;
    };
    /**
     * StatusEnum
     * @description An enumeration.
     * @enum {string}
     */
    StatusEnum: "OK" | "FAILURE" | "CRITICAL" | "UNKNOWN";
    /** TagCreation */
    TagCreation: {
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description?: string;
    };
    /** TagUpdate */
    TagUpdate: {
      /** Name */
      name?: string;
      /** Description */
      description?: string;
      /** Users */
      users?: string[];
      /** Posts */
      posts?: string[];
    };
    /** Token */
    Token: {
      /** Access Token */
      access_token: string;
      /** Token Type */
      token_type: string;
      /** Refresh Token */
      refresh_token: string;
      /** User Id */
      user_id: string;
    };
    /** UpdatePlace */
    UpdatePlace: {
      /** Title */
      title?: string;
      /** Description */
      description?: string;
      /** Location Description */
      location_description?: string;
      /** Longitude */
      longitude?: number;
      /** Latitude */
      latitude?: number;
      /** Image Urls */
      image_urls?: string[];
      /** Default Image */
      default_image?: string;
      /** Opening Hours */
      opening_hours?: string;
      /** City */
      city?: string;
      /**
       * Views
       * @default 0
       */
      views?: number;
      /** Explores */
      explores?: components["schemas"]["Explore"][];
      /** Placeactivities */
      placeActivities?: components["schemas"]["visitegypt__core__places__entities__place__PlaceActivity"][];
    };
    /** UpdatePost */
    UpdatePost: {
      /** Caption */
      caption?: string;
      /** List Of Images */
      list_of_images?: string[];
    };
    /** UploadConfirmation */
    UploadConfirmation: {
      /** Images Keys */
      images_keys: string[];
      /** Error Images */
      error_images?: string[];
      /** User Id */
      user_id: string;
    };
    /** UploadConfirmationResponse */
    UploadConfirmationResponse: {
      /** Message */
      message: string;
      /** Status Code */
      status_code: number;
    };
    /** UploadOptions */
    UploadOptions: {
      /** File Size */
      file_size?: string;
      /** Presigned Url Interval */
      presigned_url_interval?: string;
    };
    /** UploadResponse */
    UploadResponse: {
      /** Url */
      url: string;
      /** Fields */
      fields: { [key: string]: unknown };
      options?: components["schemas"]["UploadOptions"];
    };
    /** UserAuthBody */
    UserAuthBody: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** First Name */
      first_name?: string;
      /** Last Name */
      last_name?: string;
      /** Phone Number */
      phone_number?: string;
      /** Photo Link */
      photo_link?: string;
      /** Bio */
      bio?: string;
      /**
       * Birthdate
       * Format: date
       */
      birthdate?: string;
      /**
       * Interests
       * @default []
       */
      interests?: string[];
      /**
       * Followers
       * @default []
       */
      followers?: string[];
      /**
       * Following
       * @default []
       */
      following?: string[];
      /**
       * Trip Mate Requests
       * @default []
       */
      trip_mate_requests?: components["schemas"]["RequestTripMateInDB"][];
      /**
       * Fav Places
       * @default []
       */
      fav_places?: string[];
      /** Password */
      password: string;
    };
    /** UserFollowResp */
    UserFollowResp: {
      /** Followers Num */
      followers_num: string;
    };
    /** UserGoogleAuthBody */
    UserGoogleAuthBody: {
      /** Token */
      token: string;
    };
    /** UserPrefsReq */
    UserPrefsReq: {
      /** Pref List */
      pref_list: string[];
    };
    /** UserResponse */
    UserResponse: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** First Name */
      first_name?: string;
      /** Last Name */
      last_name?: string;
      /** Phone Number */
      phone_number?: string;
      /** Photo Link */
      photo_link?: string;
      /** Bio */
      bio?: string;
      /** Birthdate */
      birthdate?: string;
      /**
       * Interests
       * @default []
       */
      interests?: string[];
      /**
       * Followers
       * @default []
       */
      followers?: string[];
      /**
       * Following
       * @default []
       */
      following?: string[];
      /**
       * Trip Mate Requests
       * @default []
       */
      trip_mate_requests?: components["schemas"]["RequestTripMateInDB"][];
      /**
       * Fav Places
       * @default []
       */
      fav_places?: string[];
      /** Id */
      id: string;
      /**
       * User Role
       * @default USER
       */
      user_role?: string;
      /**
       * Xp
       * @default 0
       */
      xp?: number;
      /**
       * Badges
       * @default []
       */
      badges?: components["schemas"]["Badge"][];
      /**
       * Badge Tasks
       * @default []
       */
      badge_tasks?: components["schemas"]["visitegypt__core__accounts__entities__user__BadgeTask"][];
      /**
       * Placeactivities
       * @default []
       */
      placeActivities?: components["schemas"]["visitegypt__core__accounts__entities__user__PlaceActivity"][];
      profileFrame?: components["schemas"]["ProfileFrame"];
      /**
       * Postviews
       * @default []
       */
      postViews?: string[];
    };
    /** UserResponseInTags */
    UserResponseInTags: {
      /** Id */
      id: string;
      /** First Name */
      first_name?: string;
      /** Last Name */
      last_name?: string;
      /** Photo Link */
      photo_link?: string;
    };
    /** UserUpdate */
    UserUpdate: {
      /**
       * Email
       * Format: email
       */
      email?: string;
      /** First Name */
      first_name?: string;
      /** Last Name */
      last_name?: string;
      /** Phone Number */
      phone_number?: string;
      /** Photo Link */
      photo_link?: string;
      /**
       * Xp
       * @default 0
       */
      xp?: number;
      profileFrame?: components["schemas"]["ProfileFrame"];
      /**
       * Postviews
       * @default 0
       */
      postViews?: number;
      /** Bio */
      bio?: string;
      /** Birthdate */
      birthdate?: string;
      /** Interests */
      interests?: string[];
      /**
       * Followers
       * @default []
       */
      followers?: string[];
      /**
       * Following
       * @default []
       */
      following?: string[];
      /**
       * Trip Mate Requests
       * @default []
       */
      trip_mate_requests?: components["schemas"]["RequestTripMateInDB"][];
      /**
       * Fav Places
       * @default []
       */
      fav_places?: string[];
      /** Device Token */
      device_token?: string;
      /** Device Arn Endpoint */
      device_arn_endpoint?: string;
    };
    /** UsersPageResponse */
    UsersPageResponse: {
      /** Current Page */
      current_page: number;
      /** Content Range */
      content_range: number;
      /** Has Next */
      has_next: boolean;
      /** Users */
      users?: components["schemas"]["UserResponse"][];
    };
    /** UsersTagsReq */
    UsersTagsReq: {
      /** Tags Ids */
      tags_ids: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: string[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** chatBotBase */
    chatBotBase: {
      /** Message */
      message: string;
    };
    /** chatBotRes */
    chatBotRes: {
      /** Response */
      response: string;
    };
    /** review */
    review: {
      /** Rating */
      rating: number;
      /** Review */
      review?: string;
      /** User Id */
      user_id: string;
      /** User Name */
      user_name: string;
    };
    /** BadgeTask */
    visitegypt__core__accounts__entities__user__BadgeTask: {
      /** Badge Id */
      badge_id: string;
      /** Tasktitle */
      taskTitle: string;
      /** Progress */
      progress: number;
    };
    /** BadgeUpdate */
    visitegypt__core__accounts__entities__user__BadgeUpdate: {
      /** Progress */
      progress?: number;
      /** Owned */
      owned?: boolean;
      /** Pinned */
      pinned?: boolean;
    };
    /** PlaceActivity */
    visitegypt__core__accounts__entities__user__PlaceActivity: {
      /** Id */
      id: string;
      /** Finished */
      finished: boolean;
      /** Progress */
      progress: number;
    };
    /** BadgeTask */
    visitegypt__core__badges__entities__badge__BadgeTask: {
      /** Imgurl */
      imgUrl: string;
      /** Tasktitle */
      taskTitle: string;
      /** Max Progress */
      max_progress: number;
    };
    /** BadgeUpdate */
    visitegypt__core__badges__entities__badge__BadgeUpdate: {
      /** Img Url */
      img_url?: string;
      /** Place Id */
      place_id?: string;
      /** Max Progress */
      max_progress?: number;
      /** Title */
      title?: string;
      /** Type */
      type?: string;
      /** Xp */
      xp?: number;
      /** Description */
      description?: string;
      /** Badge Tasks */
      badge_tasks?: components["schemas"]["visitegypt__core__badges__entities__badge__BadgeTask"][];
    };
    /** PlaceActivity */
    visitegypt__core__places__entities__place__PlaceActivity: {
      /** Id */
      id: string;
      /** Xp */
      xp: number;
      /** Customxp */
      customXp: boolean;
      /** Type */
      type: number;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Duration */
      duration: string;
      /** Maxprogress */
      maxProgress: number;
    };
  };
}

export interface operations {  
  register_user_api_user_register_post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** User with this email already exists */
      409: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
  };
  reset_password_api_user_forgotpassword__email__get: {
    parameters: {
      path: {
        email: string;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  register_user_api_user_register_google_post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** User with this email already exists */
      409: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserGoogleAuthBody"];
      };
    };
  };
  get_user_api_user__get: {
    parameters: {
      query: {
        user_id?: string;
        user_email?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  update_user_api_user__user_id__put: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
  };
  delete_user_api_user__user_id__delete: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  update_user_role_api_user_role__user_id__put: {
    parameters: {
      path: {
        user_id: string;
      };
      query: {
        updated_user_role: string;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  login_user_api_user_login_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserAuthBody"];
      };
    };
  };
  login_user_api_user_login_google_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserGoogleAuthBody"];
      };
    };
  };
  get_all_users_api_user_all_get: {
    parameters: {
      query: {
        page_num?: number;
        limit?: number;
        filters?: string[];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UsersPageResponse"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  refresh_token_api_user_refresh_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
  };
  user_logout_api_user_logout__user_id__post: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  upload_user_personal_photo_api_user__user_id__upload_photo_get: {
    parameters: {
      path: {
        user_id: string;
      };
      query: {
        content_type: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UploadResponse"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  update_badge_task_progress_api_user_badge_task_put: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["visitegypt__core__accounts__entities__user__BadgeTask"];
      };
    };
  };
  update_badge_api_user_badges__badge_id__put: {
    parameters: {
      path: {
        badge_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["visitegypt__core__accounts__entities__user__BadgeUpdate"];
      };
    };
  };
  get_user_badges_api_user_badges__user_id__get: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BadgeResponse"][];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  update_place_avtivity_api_user_actvity__activity_id__put: {
    parameters: {
      path: {
        activity_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceActivityUpdate"];
      };
    };
  };
  get_user_activities_api_user_actvity__user_id__get: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  follow_user_api_user__user_id__follow_post: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserFollowResp"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  unfollow_user_api_user__user_id__unfollow_post: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserFollowResp"];
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  follow_user_api_user__user_id__mate_post: {
    parameters: {
      path: {
        user_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RequestTripMate"];
      };
    };
  };
  follow_user_api_user_trip_mate_reqs__req_id__approve_post: {
    parameters: {
      path: {
        req_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  add_prefs_user_api_user_interests_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserPrefsReq"];
      };
    };
  };
  follow_user_api_user_interests_delete_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** The user was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The user was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserPrefsReq"];
      };
    };
  };
  get_items_api_item__get: {
    parameters: {
      query: {
        page_num?: number;
        limit?: number;
        filters?: string[];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ItemsPageResponse"];
        };
      };
      /** The item was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The item was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  add_new_item_api_item__post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ItemInDB"];
        };
      };
      /** The item was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The item was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemBase"];
      };
    };
  };
  update_item_api_item__item_id__put: {
    parameters: {
      path: {
        item_id: string;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ItemInDB"];
        };
      };
      /** The item was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The item was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ItemUpdate"];
      };
    };
  };
  delete_item_api_item__item_id__delete: {
    parameters: {
      path: {
        item_id: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** The item was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The item was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  get_places_api_place__get: {
    parameters: {
      query: {
        page_num?: number;
        limit?: number;
        filters?: string[];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlacesPageResponse"];
        };
      };
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  add_new_place_api_place__post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PlaceInDB"];
        };
      };
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceBase"];
      };
    };
  };
  get_some_places_api_place_activityid_get: {
    parameters: {
      query: {
        id?: string[];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlaceInDB"][];
        };
      };
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  get_place_by_title_api_place_title_get: {
    parameters: {
      query: {
        place_title: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlaceInDB"];
        };
      };
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  get_place_by_id_api_place__place_id__get: {
    parameters: {
      path: {
        place_id: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlaceInDB"];
        };
      };
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  update_place_api_place__place_id__put: {
    parameters: {
      path: {
        place_id: string;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PlaceInDB"];
        };
      };
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePlace"];
      };
    };
  };
  delete_place_api_place__place_id__delete: {
    parameters: {
      path: {
        place_id: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  get_place_by_id_api_place_city__city_name__get: {
    parameters: {
      path: {
        city_name: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PlacesPageResponse"];
        };
      };
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  add_new_review_api_place_review__place_id__post: {
    parameters: {
      path: {
        place_id: unknown;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["review"];
      };
    };
  };
  delete_review_api_place_review__place_id__delete: {
    parameters: {
      path: {
        place_id: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["review"];
      };
    };
  };
  get_cities_api_place_cities_all_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown[];
        };
      };
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  add_to_favs_api_place_favs__place_id__post: {
    parameters: {
      path: {
        place_id: string;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  remove_from_favs_api_place_favs__place_id__delete: {
    parameters: {
      path: {
        place_id: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** The place was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The place was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  get_posts_api_post__get: {
    parameters: {
      query: {
        page_num?: number;
        limit?: number;
        filters?: string[];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PostsPageResponse"];
        };
      };
      /** The post was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The post was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  add_new_post_api_post__post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PostInDB"];
        };
      };
      /** The post was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The post was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PostBase"];
      };
    };
  };
  update_post_api_post__post_id__put: {
    parameters: {
      path: {
        post_id: string;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PostInDB"];
        };
      };
      /** The post was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The post was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePost"];
      };
    };
  };
  delete_post_api_post__post_id__delete: {
    parameters: {
      path: {
        post_id: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** The post was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The post was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  add_new_like_api_post_like__post_id__post: {
    parameters: {
      path: {
        post_id: unknown;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** The post was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The post was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  delete_post_like_api_post_like__post_id__delete: {
    parameters: {
      path: {
        post_id: unknown;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": unknown;
        };
      };
      /** The post was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The post was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  upload_post_photo_api_post__post_id__upload_photo_get: {
    parameters: {
      path: {
        post_id: string;
      };
      query: {
        content_type: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UploadResponse"];
        };
      };
      /** The post was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The post was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  get_chatbot_api_chatbot__post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["chatBotRes"];
        };
      };
      /** The chatbot was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The chatbot was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["chatBotBase"];
      };
    };
  };
  confirm_upload_api_upload_confirm_upload_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UploadConfirmationResponse"];
        };
      };
      /** The upload was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The upload was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadConfirmation"];
      };
    };
  };
  get_items_api_badge__get: {
    parameters: {
      query: {
        page_num?: number;
        limit?: number;
        filters?: string[];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BadgesPageResponse"];
        };
      };
      /** The badge was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The badge was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  add_new_badge_api_badge__post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["BadgeInDB"];
        };
      };
      /** The badge was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The badge was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BadgeBase"];
      };
    };
  };
  update_badge_api_badge__badge_id__put: {
    parameters: {
      path: {
        badge_id: string;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["BadgeInDB"];
        };
      };
      /** The badge was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The badge was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["visitegypt__core__badges__entities__badge__BadgeUpdate"];
      };
    };
  };
  delete_badge_api_badge__badge_id__delete: {
    parameters: {
      path: {
        badge_id: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** The badge was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The badge was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  get_tags_api_tag__get: {
    parameters: {
      query: {
        page_num?: number;
        limit?: number;
        filters?: string[];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GetTagResponse"][];
        };
      };
      /** The tag was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The tag was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  add_tag_api_tag__post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["GetTagResponse"];
        };
      };
      /** The tag was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The tag was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TagCreation"];
      };
    };
  };
  update_tag_api_tag__tag_id__put: {
    parameters: {
      path: {
        tag_id: string;
      };
    };
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["GetTagResponse"];
        };
      };
      /** The tag was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The tag was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TagUpdate"];
      };
    };
  };
  delete_post_api_tag__tag_id__delete: {
    parameters: {
      path: {
        tag_id: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** The tag was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The tag was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
  };
  get_tags_api_tag_users_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponseInTags"][];
        };
      };
      /** The tag was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The tag was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UsersTagsReq"];
      };
    };
  };
  register_token_api_notification_register_device_post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["RegisterDeviceTokenResponse"];
        };
      };
      /** The push notifcation was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The push notifcation was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDeviceTokenRequest"];
      };
    };
  };
  send_notification_api_notification_send_post: {
    responses: {
      /** Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["NotificationSentResponse"];
        };
      };
      /** The push notifcation was not authenticated */
      401: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** The push notifcation was not found */
      404: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
      /** Internal Server Error */
      500: {
        content: {
          "application/json": components["schemas"]["HTTPErrorModel"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Notification"];
      };
    };
  };
  /** Performs health check and returns information about running service. */
  health_check_api_status_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthCheck"];
        };
      };
    };
  };
}

export interface external {}
